trigger:
  - main
pool:
  vmImage: ubuntu-latest
steps:
  - script: >-
      response=$(curl -s -o /dev/null -w "%{http_code}"
      https://q2rjbj8eoj.execute-api.us-east-1.amazonaws.com/gatecheck?source=azure&pipelineId=4&tenantId=02e24def-3903-4979-85b7-757a612cc3af);
      if [ "$response" -ne 200 ]; then exit 1; fi
    displayName: ASPM Gate Check
  - task: NodeTool@0
    inputs:
      versionSpec: 10.x
    displayName: Install Node.js
  - script: |
      npm install
      npm run build
    displayName: npm install and build
